"""empty message

Revision ID: 2c4d57ac4162
Revises: 9daf349218d0
Create Date: 2023-05-27 03:25:45.439602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4d57ac4162'
down_revision = '9daf349218d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=True),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('carrer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
